### ISSUE TITLE
Integrate Python {unit, acceptance} tests in CI (Github workflow)

### ISSUE THREAD

**Issue by doyu** [Origami-TinyML/tflm_hello_world#10]
https://github.com/Origami-TinyML/tflm_hello_world/blob/main/README.md#sprint-1

**Comment by doyu** [comment]
@matiasto Leevi is quite familiar with Docker. He could help for putting things in Docker here. Or you could take a look at his previous commit of Docker in the git history too. I put him on this issue. You can ask him here.

**Comment by matiasto** [comment]
I managed the Docker problems, but next time, I'll immediately contact Leevi.

One thing I was thinking about was the test scope. Some of the tests in Tensorflow package won't run in our version of Python3 (syntax problems such as "is" instead of "=="). With that in mind, could the first version look like the RobotFrameworks; own folder for the tests? We can fine-tune the system further down the line.

**Comment by matiasto** [comment]
Just for the record, this command was quite useful:
```bash
docker container run -it <name of the docker image> bash
```

**Comment by matiasto** [comment]
Now that nbdev tests are set up, should I implement only pytest to workflow? How about coverage?

**Comment by doyu** [comment]
You can take 2 steps here, one for execting pytest and another for displaying coverage in codecov?

**Comment by doyu** [comment]
You can take 2 steps here, one for execting pytest and another for displaying coverage in codecov?
